### ISSUE TITLE
while adding products dependencies showing wrong when we edit.

### ISSUE THREAD

**Issue by SarfrazS** [ladybirdweb/agora-invoicing-community#1568]
It is showing link that which is not Json format
![image](https://user-images.githubusercontent.com/18435376/104315224-a2863f00-5500-11eb-8c50-d9b3827d0c69.png)

**Comment by sandesh556** [comment]
This is only present for one upload in billing. it has happened because it was uploaded in that format. We just need to just update it and it will work fine. 

{"extensions": {"optional": ["ldap", "redis", "ionCube Loader", "soap"], "required": ["curl", "ctype", "imap", "mbstring", "openssl","tokenizer", "pdo_mysql", "zip", "pdo", "mysqli", "bcmath", "iconv", "XML", "json", "fileinfo", "gd"]}, "requisites": ["Establish connection to Helpdesk License Manager", "PHP Version", "Database version", "PHP exec function", "env", "max_execution_time", "allow_url_fopen", "cURL", "app_url", "ssl_certificate"], "min_php_version": "7.3.1", "min_mysql_version": [50700, "v5.7.0"],"max_mysql_version": [50799, "v5.7.*"], "min_mariadb_version":[100300, "v10.3"],"max_mariadb_version":[100600,"v10.6"]}

Also try uploading new version using these dependencies it seems to be working fine
